id: A45483BE6
title: 'A Garland of Vajra Words: A Prayer to the Guru'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.317895
  last_modified_at: 2022-03-01 03:51:01.317897
