id: A45483BE6
title: A Short Prayer to the Abbot, the Master and the King
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.339969
  last_modified_at: 2022-03-01 03:51:01.339972
