id: A45483BE6
title: 'Cloud Banks of Blessings: A Prayer to Guru Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.358700
  last_modified_at: 2022-03-01 03:51:01.358703
