id: A45483BE6
title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of Glory'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.425295
  last_modified_at: 2022-03-01 03:51:01.425298
