id: A45483BE6
title: 'The Swift Fulfilment of Aspirations: A Prayer to Glorious Orgyen, King of
  Dharma'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.430372
  last_modified_at: 2022-03-01 03:51:01.430375
