id: A45483BE6
title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.419128
  last_modified_at: 2022-03-01 03:51:01.419131
