id: A45483BE6
title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of Uḍḍiyāna'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.427481
  last_modified_at: 2022-03-01 03:51:01.427484
