id: A45483BE6
title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
  Mountain of Glory
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.373366
  last_modified_at: 2022-03-01 03:51:01.373369
