id: A45483BE6
title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.362980
  last_modified_at: 2022-03-01 03:51:01.362983
