id: A45483BE6
title: Recollecting the Deeds of The Tenth Days
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.370047
  last_modified_at: 2022-03-01 03:51:01.370049
