id: A45483BE6
title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from the Extremely
  Secret Assembly of Sugatas)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.333302
  last_modified_at: 2022-03-01 03:51:01.333305
