id: A45483BE6
title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.328697
  last_modified_at: 2022-03-01 03:51:01.328700
