id: A45483BE6
title: Prayer to Pema Tötreng Tsal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.367693
  last_modified_at: 2022-03-01 03:51:01.367695
