id: A45483BE6
title: A Prayer to the Vajradhara of Oḍḍiyāna
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.338823
  last_modified_at: 2022-03-01 03:51:01.338826
