id: A45483BE6
title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills All
  Wishes
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.416670
  last_modified_at: 2022-03-01 03:51:01.416672
