id: A45483BE6
title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously Fulfils
  All Wishes (Sampa Lhundrupma)'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.393304
  last_modified_at: 2022-03-01 03:51:01.393308
