id: A45483BE6
title: The General Visualization for Prayers to Guru Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.389012
  last_modified_at: 2022-03-01 03:51:01.389014
