id: A45483BE6
title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.361591
  last_modified_at: 2022-03-01 03:51:01.361593
