id: A45483BE6
title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.368657
  last_modified_at: 2022-03-01 03:51:01.368660
