id: A45483BE6
title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche and
  the Twenty-Five Disciples, the King and Subjects'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.391044
  last_modified_at: 2022-03-01 03:51:01.391047
