id: A45483BE6
title: The Prayer to Guru Rinpoche for Attainments
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.408795
  last_modified_at: 2022-03-01 03:51:01.408798
