id: A45483BE6
title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.326151
  last_modified_at: 2022-03-01 03:51:01.326154
