id: A45483BE6
title: Prayer to Orgyen Rinpoche Invoking His Wisdom Mind
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.365830
  last_modified_at: 2022-03-01 03:51:01.365833
