id: A45483BE6
title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.423197
  last_modified_at: 2022-03-01 03:51:01.423200
