id: A45483BE6
title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.314645
  last_modified_at: 2022-03-01 03:51:01.314651
