id: A45483BE6
title: The Prayer to Swiftly Fulfil All Wishes
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.420541
  last_modified_at: 2022-03-01 03:51:01.420544
