id: A45483BE6
title: A Heart Prayer to Orgyen Dorje Chang
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.319518
  last_modified_at: 2022-03-01 03:51:01.319521
