id: A45483BE6
title: Threefold Aspiration for Rebirth in Zangdok Palri
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.445671
  last_modified_at: 2022-03-01 03:51:01.445674
