id: A45483BE6
title: A Plaintive Prayer to Guru Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.321737
  last_modified_at: 2022-03-01 03:51:01.321739
