id: A45483BE6
title: 'The Fulfilment of Wishes and Aspirations: A Prayer to Ācārya Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.387675
  last_modified_at: 2022-03-01 03:51:01.387678
