id: A45483BE6
title: The Prayer in Six Vajra Lines
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.400087
  last_modified_at: 2022-03-01 03:51:01.400090
