id: A45483BE6
title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.366735
  last_modified_at: 2022-03-01 03:51:01.366737
