id: A45483BE6
title: The Prayer which is the Source of All True Realization
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.422218
  last_modified_at: 2022-03-01 03:51:01.422221
