id: A45483BE6
title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.342477
  last_modified_at: 2022-03-01 03:51:01.342480
