id: A45483BE6
title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils All Wishes
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.352919
  last_modified_at: 2022-03-01 03:51:01.352922
