id: A45483BE6
title: A Synopsis of Guru Padmasambhava’s Life
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.340943
  last_modified_at: 2022-03-01 03:51:01.340946
