id: A45483BE6
title: A Yearning Plea to the Precious Guru
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.344329
  last_modified_at: 2022-03-01 03:51:01.344332
