id: A45483BE6
title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in Eight
  Chapters'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.350321
  last_modified_at: 2022-03-01 03:51:01.350324
