id: A45483BE6
title: A Prayer of Devotion, to Make the Tears Fall
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.331113
  last_modified_at: 2022-03-01 03:51:01.331116
