id: A45483BE6
title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen Rinpoche,
  Embodiment of All Sources of Refuge'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.455153
  last_modified_at: 2022-03-01 03:51:01.455156
