id: A45483BE6
title: Prayer of the Wisdom Mind
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.364809
  last_modified_at: 2022-03-01 03:51:01.364812
