id: A45483BE6
title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles from the
  Path
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.351936
  last_modified_at: 2022-03-01 03:51:01.351939
