id: A45483BE6
title: 'The Beat of the Vajra Drum: A Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.381777
  last_modified_at: 2022-03-01 03:51:01.381780
