id: A45483BE6
title: The Testament Prayer to Orgyen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.432361
  last_modified_at: 2022-03-01 03:51:01.432364
