id: A45483BE6
title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
  the Precious Master of Oddiyana'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.462470
  last_modified_at: 2022-03-01 03:51:01.462473
