id: A45483BE6
title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.406680
  last_modified_at: 2022-03-01 03:51:01.406683
