id: A45483BE6
title: 'The Wish-Fulfilling Tree: A Prayer to the All-Embodying Lama Tsokye Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.433604
  last_modified_at: 2022-03-01 03:51:01.433606
