id: A45483BE6
title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.426430
  last_modified_at: 2022-03-01 03:51:01.426433
