id: A45483BE6
title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom for
  the Swift Fulfilment of Wishes'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.459156
  last_modified_at: 2022-03-01 03:51:01.459159
