id: A45483BE6
title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:01.323103
  last_modified_at: 2022-03-01 03:51:01.323106
